<a href="https://colab.research.google.com/github/Ayushcode04/codemypandas-pytrch/blob/main/Pytorchbase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

# ***List***

In [ ]:
mylist=[[1,2,3],[3,4,5]]
mylist

# *Numpy arrays*

In [ ]:
np1=np.random.rand(3,4)
np1

array([[0.75192826, 0.80671869, 0.97032917, 0.89712021],
       [0.9140961 , 0.92071203, 0.1977391 , 0.75310918],
       [0.92286357, 0.20405852, 0.98352387, 0.68111689]])

# ***Tensor***

In [ ]:
tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[-0.0026, -0.3525, -0.6518,  0.1556],
        [-0.1788, -0.3909, -1.2529, -0.1428],
        [ 0.2091, -1.7221,  0.5269, -0.5517]])

In [ ]:
tensor_3d=torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# create tensor of np
my_tensor=torch.tensor(np1)
my_tensor

tensor([[0.7519, 0.8067, 0.9703, 0.8971],
        [0.9141, 0.9207, 0.1977, 0.7531],
        [0.9229, 0.2041, 0.9835, 0.6811]], dtype=torch.float64)

# ***ops***

In [ ]:
my_torch=torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# reshape and view
my_torch=my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# reshape if we dont know the no. of items using -1
my_torch2=torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
my_torch2=my_torch2.reshape(-1,5)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [35]:
my_torch3=my_torch2.view(3,-1)
my_torch3

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [44]:
my_torch4=torch.arange(10)

In [45]:
my_torch4[1]=4242
my_torch4

tensor([   0, 4242,    2,    3,    4,    5,    6,    7,    8,    9])

In [46]:
# Slices
my_torch7=torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
# grab item
my_torch7[7]

tensor(7)

In [48]:
# grab slice
my_torch8=my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [50]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [53]:
# return col
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

# ***Tensor math***

In [55]:
tensor_a =torch.tensor([1,2,3,4])
tensor_b =torch.tensor([5,6,7,8])

In [57]:
# add
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [59]:
# add longform
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [60]:
# substraction sub(),mul(),div(),rem(),pow()a**b,
tensor_a - tensor_b

tensor([-4, -4, -4, -4])